### ISSUE TITLE
Are install instructions accurate?

### ISSUE THREAD

**Issue by Gideonnn** [elgatosf/streamdeck-plugin-template#8]
I followed the exact steps in the README.md but the plugin doesnt show up on the Elgato Stream Deck.app on my macbook. I see old versions needed the DestributionTool, is this still the case? How can I debug this? I am not sure if restarting the Stream Deck application is enough to get the plugin to show.

**Comment by wtfspm** [comment]
@Gideonnn I ran into the same issue and it was because the symlink step isn't quite right. The path to the plugin folder has to be fully qualified for the symlink to be valid.

The instructions say this:
`ln -s com.example.my-plugin.sdPlugin ~/Library/Application\ Support/com.elgato.StreamDeck/Plugins/`

It should be more like this:
`ln -s /Users/whatever/streamdeck-plugin-template/src/com.example.my-plugin.sdPlugin ~/Library/Application\ Support/com.elgato.StreamDeck/Plugins/`

I'm having trouble getting the actions to do anything, but at least it shows up on the deck.

**Comment by ChekTek** [comment]
Hi,

Thanks for pointing this out! We recently fixed our [getting started guide](https://docs.elgato.com/sdk/plugins/getting-started) to fix the symlink commands.
